name: "godot-ci export"
on: push

permissions:
  contents: read
  pages: write
  id-token: write

env:
  GODOT_VERSION: 3.5.2
  RELEASE_NAME: rc2

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download Godot
        run: |
          wget https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/${RELEASE_NAME}/Godot_v${GODOT_VERSION}-${RELEASE_NAME}_linux_headless.64.zip
          wget https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/${RELEASE_NAME}/Godot_v${GODOT_VERSION}-${RELEASE_NAME}_export_templates.tpz
          unzip Godot_v${GODOT_VERSION}-${RELEASE_NAME}_linux_headless.64.zip
          mv Godot_v${GODOT_VERSION}-${RELEASE_NAME}_linux_headless.64 godot
          unzip Godot_v${GODOT_VERSION}-${RELEASE_NAME}_export_templates.tpz
          mkdir -p ~/.local/share/godot/templates/${GODOT_VERSION}.${RELEASE_NAME}
          mv templates/* ~/.local/share/godot/templates/${GODOT_VERSION}.${RELEASE_NAME}
      - name: Web Build
        run: |
          mkdir -v -p build/web
          chmod +x ./godot
          ./godot -v --export "HTML5" ./build/web/index.html
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: web
          path: build/web
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: 'build/web'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
